
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory into the container for live updates during development
    environment:
      PYTHONPATH: /app/src
    command: uvicorn src.backend.main:app --host 0.0.0.0 --port 8000 --reload
